spring.application.name=coral-planner-api

spring.profiles.include=secret
# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/crops_by_season
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.web.error.include-message=always
spring.web.error.include-binding-errors=always